[package]
name = "fog_of_war_chess"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
mpclib = {tag="zw/test-errors", git = "https://github.com/zac-williamson/mpclib" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
protocol_types = { tag = "v3.0.0-devnet.6-patch.1", git = "https://github.com/AztecProtocol/aztec-packages/", directory="noir-projects/noir-protocol-circuits/crates/types"}
# mpclib = {tag="v0.3.1", git = "https://github.com/zac-williamson/mpclib"}
