[package]
name = "fog_of_war_chess"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
mpclib = {path = "../mpclib"}
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }

# mpclib = {tag="v0.3.1", git = "https://github.com/zac-williamson/mpclib"}
